/**
 * server/proxy.mjs
 * WorldView flight data proxy — viewport-aware, on-demand hub fetching.
 *
 * The browser sends the visible bounding box with each request:
 *   GET /api/flights?bounds=minLon,minLat,maxLon,maxLat
 *
 * The proxy computes which 250nm-radius hubs overlap that bbox, fetches only
 * those hubs from opendata.adsb.fi, merges results into a persistent DB, and
 * returns the full DB snapshot filtered to the bbox.
 *
 * Hub results are cached individually per hub (TTL: 12s) so panning doesn't
 * re-fetch hubs that were just queried. The DB also retains aircraft globally
 * so previously-seen aircraft outside the viewport are preserved for when the
 * user pans back.
 *
 * Start:  node server/proxy.mjs
 */

import http from 'http';

const PORT       = 3001;
const RADIUS_NM  = 250;
const RADIUS_DEG = RADIUS_NM / 60;   // ~4.17 degrees
const HUB_TTL    = 12_000;            // ms — don't re-fetch a hub more often than this
const STALE_MS   = 120_000;           // remove aircraft not seen for 2 minutes
const MAX_CONC   = 12;                // max concurrent hub fetches per request

const HEADERS = { 'User-Agent': 'WorldView/0.1 (github.com/JerichoJack/WorldView)' };

// ── Hub grid — mathematically tiled at 250nm radius with ~30% overlap ─────────
// Generated by: lat step = RADIUS_DEG * 1.4, lon step = lat_step / cos(lat)

function generateHubGrid() {
  const LAT_STEP = RADIUS_DEG * 1.4;
  const hubs = [];
  let lat = -70 + LAT_STEP / 2;
  while (lat <= 83) {
    const cosLat  = Math.max(Math.cos(lat * Math.PI / 180), 0.08);
    const lonStep = Math.min(LAT_STEP / cosLat, 360);
    let lon = -180;
    while (lon < 180) {
      let normLon = lon % 360;
      if (normLon > 180) normLon -= 360;
      hubs.push({ lat: Math.round(lat * 10) / 10, lon: Math.round(normLon * 10) / 10 });
      lon += lonStep;
    }
    lat += LAT_STEP;
  }
  return hubs;
}

const ALL_HUBS = generateHubGrid();
console.log(`[proxy] Hub grid: ${ALL_HUBS.length} hubs at ${RADIUS_NM}nm radius`);

// ── Per-hub fetch cache (avoid re-fetching hubs that were just queried) ────────
/** @type {Map<string, { time: number, promise?: Promise }>} */
const hubCache = new Map();

function hubKey(hub) { return `${hub.lat},${hub.lon}`; }

// ── Aircraft database ─────────────────────────────────────────────────────────
/** @type {Map<string, object>} */
const db = new Map();

function upsert(aircraft) {
  const now = Date.now();
  for (const a of aircraft) {
    const id = (a.hex ?? '').toLowerCase().trim();
    if (!id || !a.lat || !a.lon) continue;
    if (a.alt_baro === 'ground' || (a.alt_baro ?? 0) <= 100) continue;
    db.set(id, {
      hex:      id,
      flight:   (a.flight ?? a.r ?? '').trim(),
      lat:      a.lat,
      lon:      a.lon,
      alt_baro: a.alt_baro ?? a.alt_geom ?? 10000,
      track:    a.track ?? 0,
      gs:       a.gs ?? 0,
      // enrichment fields — used for icon shape, color classification, HUD panel
      t:        a.t        ?? '',       // ICAO type code e.g. "H60", "B738", "A320"
      category: a.category ?? '',       // ADS-B category byte e.g. "A7" = rotorcraft
      dbFlags:  a.dbFlags  ?? 0,        // bit 0 = military
      squawk:   a.squawk   ?? '',
      baro_rate: a.baro_rate ?? a.geom_rate ?? 0,
      _seen:    now,
    });
  }
}

function pruneStale() {
  const cutoff = Date.now() - STALE_MS;
  let n = 0;
  for (const [id, a] of db) { if (a._seen < cutoff) { db.delete(id); n++; } }
  if (n) console.log(`[proxy] Pruned ${n} — DB: ${db.size}`);
}

setInterval(pruneStale, 30_000);

// ── Hub selection — find hubs that overlap the viewport bbox ──────────────────

function hubsForBounds(minLon, minLat, maxLon, maxLat) {
  // Pad the bbox by one hub radius so we catch aircraft near the edges
  const pad = RADIUS_DEG * 1.1;
  const pMinLat = minLat - pad, pMaxLat = maxLat + pad;
  const pMinLon = minLon - pad, pMaxLon = maxLon + pad;
  const wraps = pMaxLon - pMinLon >= 360; // full globe visible

  return ALL_HUBS.filter(h => {
    if (h.lat < pMinLat || h.lat > pMaxLat) return false;
    if (wraps) return true;
    if (pMinLon < -180 || pMaxLon > 180) {
      // bbox wraps antimeridian
      return h.lon >= pMinLon + 360 || h.lon <= pMaxLon - 360 ||
             (h.lon >= pMinLon && h.lon <= pMaxLon);
    }
    return h.lon >= pMinLon && h.lon <= pMaxLon;
  });
}

// ── Hub fetcher with per-hub TTL cache ────────────────────────────────────────

async function fetchHub(hub) {
  const key = hubKey(hub);
  const cached = hubCache.get(key);

  // Return cached promise if hub was recently fetched
  if (cached) {
    if (cached.promise) return cached.promise; // in-flight
    if (Date.now() - cached.time < HUB_TTL) return; // fresh, skip
  }

  const promise = (async () => {
    try {
      const url = `https://opendata.adsb.fi/api/v3/lat/${hub.lat}/lon/${hub.lon}/dist/${RADIUS_NM}`;
      const res = await fetch(url, { headers: HEADERS, signal: AbortSignal.timeout(8_000) });
      if (!res.ok) throw new Error(`${res.status}`);
      const d = await res.json();
      upsert(d.aircraft ?? d.ac ?? []);
    } catch (err) {
      // Silently ignore individual hub failures
    } finally {
      hubCache.set(key, { time: Date.now(), promise: null });
    }
  })();

  hubCache.set(key, { time: Date.now(), promise });
  return promise;
}

// ── Request handler ───────────────────────────────────────────────────────────

async function handleFlights(query, res) {
  let hubs = [];

  if (query.bounds) {
    const parts = query.bounds.split(',').map(Number);
    if (parts.length === 4 && parts.every(n => !isNaN(n))) {
      const [minLon, minLat, maxLon, maxLat] = parts;
      hubs = hubsForBounds(minLon, minLat, maxLon, maxLat);
    }
  }

  // Limit concurrency
  const limited = hubs.slice(0, MAX_CONC * 4); // fetch up to 48 hubs per request
  const batches = [];
  for (let i = 0; i < limited.length; i += MAX_CONC) {
    batches.push(limited.slice(i, i + MAX_CONC));
  }
  for (const batch of batches) {
    await Promise.allSettled(batch.map(h => fetchHub(h)));
  }

  // Return DB filtered to the requested bbox (plus a small buffer)
  let aircraft = [...db.values()].map(({ _seen, ...rest }) => rest);

  if (query.bounds) {
    const [minLon, minLat, maxLon, maxLat] = query.bounds.split(',').map(Number);
    aircraft = aircraft.filter(a =>
      a.lat >= minLat - 1 && a.lat <= maxLat + 1 &&
      a.lon >= minLon - 1 && a.lon <= maxLon + 1
    );
  }

  console.log(`[proxy] ${hubs.length} hubs queried → ${aircraft.length} aircraft in viewport`);

  res.writeHead(200);
  res.end(JSON.stringify({ aircraft, total: aircraft.length, ts: Date.now() }));
}

// ── HTTP server ───────────────────────────────────────────────────────────────

const server = http.createServer(async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Content-Type', 'application/json');
  if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }

  const [path, qs] = req.url.split('?');
  const query = Object.fromEntries(new URLSearchParams(qs ?? ''));
  const url   = path.replace(/\/$/, '');

  if (url === '/api/flights') {
    await handleFlights(query, res);
  } else if (url === '/health') {
    res.writeHead(200);
    res.end(JSON.stringify({ status: 'ok', db: db.size, hubs: ALL_HUBS.length, hub_cache: hubCache.size }));
  } else {
    res.writeHead(404);
    res.end(JSON.stringify({ error: 'Not found' }));
  }
});

server.listen(PORT, () => {
  console.log(`[proxy] WorldView → http://localhost:${PORT}/api/flights?bounds=minLon,minLat,maxLon,maxLat`);
});
