/**
 * server/proxy.mjs
 * ShadowGrid flight data proxy — viewport-aware, on-demand hub fetching.
 *
 * The browser sends the visible bounding box with each request:
 *   GET /api/flights?bounds=minLon,minLat,maxLon,maxLat
 *
 * The proxy computes which 250nm-radius hubs overlap that bbox, fetches only
 * those hubs from opendata.adsb.fi, merges results into a persistent DB, and
 * returns the full DB snapshot filtered to the bbox.
 *
 * Hub results are cached individually per hub (TTL: 12s) so panning doesn't
 * re-fetch hubs that were just queried. The DB also retains aircraft globally
 * so previously-seen aircraft outside the viewport are preserved for when the
 * user pans back.
 *
 * Start:  node server/proxy.mjs
 */

import http from 'http';
import fs from 'fs';
import path from 'path';
import * as satellite from 'satellite.js';

const PORT       = 3001;
const RADIUS_NM  = 250;
const RADIUS_DEG = RADIUS_NM / 60;   // ~4.17 degrees
const SERVER_HEAVY_MODE = /^(1|true|yes)$/i.test(
  process.env.SHADOWGRID_SERVER_HEAVY ?? process.env.SHADOWGRID_SERVER_MODE ?? ''
);
const HUB_TTL    = SERVER_HEAVY_MODE ? 8_000 : 12_000;    // ms — don't re-fetch a hub more often than this
const STALE_MS   = SERVER_HEAVY_MODE ? 300_000 : 120_000; // keep aircraft longer in heavy mode
const MAX_CONC   = SERVER_HEAVY_MODE ? 24 : 12;           // max concurrent hub fetches per request

const HEADERS = { 'User-Agent': 'ShadowGrid/0.1 (github.com/JerichoJack/ShadowGrid)' };

function loadDotEnvVars() {
  const envPath = path.resolve(process.cwd(), '.env');
  if (!fs.existsSync(envPath)) return new Map();
  const lines = fs.readFileSync(envPath, 'utf8').split(/\r?\n/);
  const out = new Map();
  for (const line of lines) {
    const s = line.trim();
    if (!s || s.startsWith('#')) continue;
    const i = s.indexOf('=');
    if (i <= 0) continue;
    const key = s.slice(0, i).trim();
    const val = s.slice(i + 1).trim();
    out.set(key, val);
  }
  return out;
}

const DOTENV_VARS = loadDotEnvVars();
const GOOGLE_ROUTES_KEY = process.env.VITE_GOOGLE_MAPS_API_KEY || DOTENV_VARS.get('VITE_GOOGLE_MAPS_API_KEY') || '';
const BACKEND_FLIGHT_PROVIDER = (process.env.VITE_FLIGHT_PROVIDER || DOTENV_VARS.get('VITE_FLIGHT_PROVIDER') || 'proxy').toLowerCase();
const BACKEND_SATELLITE_PROVIDER = (process.env.VITE_SATELLITE_PROVIDER || DOTENV_VARS.get('VITE_SATELLITE_PROVIDER') || 'celestrak').toLowerCase();
const SPACETRACK_USER = process.env.VITE_SPACETRACK_USERNAME || DOTENV_VARS.get('VITE_SPACETRACK_USERNAME') || '';
const SPACETRACK_PASS = process.env.VITE_SPACETRACK_PASSWORD || DOTENV_VARS.get('VITE_SPACETRACK_PASSWORD') || '';

// ── Satellite snapshot cache (server-side propagation mode) ─────────────────
const SAT_CATALOG_TTL_MS = 10 * 60_000;
const SAT_SNAPSHOT_POLL_TIMEOUT_MS = 8000;
let satCatalogTs = 0;
/** @type {Array<{id:string,name:string,satrec:any}>} */
let satCatalog = [];
let satCatalogSource = 'unknown';

// ── Hub grid — mathematically tiled at 250nm radius with ~30% overlap ─────────
// Generated by: lat step = RADIUS_DEG * 1.4, lon step = lat_step / cos(lat)

function generateHubGrid() {
  const LAT_STEP = RADIUS_DEG * 1.4;
  const hubs = [];
  let lat = -70 + LAT_STEP / 2;
  while (lat <= 83) {
    const cosLat  = Math.max(Math.cos(lat * Math.PI / 180), 0.08);
    const lonStep = Math.min(LAT_STEP / cosLat, 360);
    let lon = -180;
    while (lon < 180) {
      let normLon = lon % 360;
      if (normLon > 180) normLon -= 360;
      hubs.push({ lat: Math.round(lat * 10) / 10, lon: Math.round(normLon * 10) / 10 });
      lon += lonStep;
    }
    lat += LAT_STEP;
  }
  return hubs;
}

const ALL_HUBS = generateHubGrid();
console.log(`[proxy] Hub grid: ${ALL_HUBS.length} hubs at ${RADIUS_NM}nm radius`);

// ── Per-hub fetch cache (avoid re-fetching hubs that were just queried) ────────
/** @type {Map<string, { time: number, promise?: Promise }>} */
const hubCache = new Map();

function hubKey(hub) { return `${hub.lat},${hub.lon}`; }

function boundsToQueryCenter(bounds) {
  if (!bounds) return null;
  const [minLon, minLat, maxLon, maxLat] = bounds;
  if (![minLon, minLat, maxLon, maxLat].every(Number.isFinite)) return null;

  let lonSpan = maxLon - minLon;
  if (lonSpan < 0) lonSpan += 360;
  const latSpan = Math.max(0, maxLat - minLat);

  let centerLon = minLon + lonSpan / 2;
  if (centerLon > 180) centerLon -= 360;
  const centerLat = minLat + latSpan / 2;

  const kmPerDegLat = 111.32;
  const kmPerDegLon = 111.32 * Math.max(Math.cos(centerLat * Math.PI / 180), 0.1);
  const diagKm = Math.hypot(latSpan * kmPerDegLat, lonSpan * kmPerDegLon);
  const radiusNm = Math.min(250, Math.max(75, Math.round((diagKm / 1.852) * 0.6)));

  return { lat: centerLat, lon: centerLon, distNm: radiusNm };
}

async function fetchReadsbProvider(baseUrl, bounds, globalMode = false) {
  // In global mode (server-heavy, no-limit stress test) use the /v2/all endpoint.
  let url;
  if (globalMode) {
    url = `${baseUrl}/v2/all`;
  } else {
    const center = boundsToQueryCenter(bounds);
    if (center) {
      url = `${baseUrl}/v2/lat/${center.lat.toFixed(4)}/lon/${center.lon.toFixed(4)}/dist/${center.distNm}`;
    } else {
      url = `${baseUrl}/v2/point/0/0/250`;
    }
  }

  const resp = await fetch(url, { headers: HEADERS, signal: AbortSignal.timeout(20_000) });
  if (!resp.ok) throw new Error(`${baseUrl} ${resp.status}`);
  const data = await resp.json();
  upsert(data.aircraft ?? data.ac ?? []);
}

function toRad(d) { return d * Math.PI / 180; }
function toDeg(r) { return r * 180 / Math.PI; }

function gcDistanceMeters(lat1, lon1, lat2, lon2) {
  const R = 6371000;
  const p1 = toRad(lat1);
  const p2 = toRad(lat2);
  const dp = toRad(lat2 - lat1);
  const dl = toRad(lon2 - lon1);
  const a = Math.sin(dp / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dl / 2) ** 2;
  return 2 * R * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function decodeGooglePolyline(encoded) {
  const coords = [];
  let index = 0;
  let lat = 0;
  let lon = 0;

  while (index < encoded.length) {
    let shift = 0;
    let result = 0;
    let byte;
    do {
      byte = encoded.charCodeAt(index++) - 63;
      result |= (byte & 0x1f) << shift;
      shift += 5;
    } while (byte >= 0x20);
    lat += (result & 1) ? ~(result >> 1) : (result >> 1);

    shift = 0;
    result = 0;
    do {
      byte = encoded.charCodeAt(index++) - 63;
      result |= (byte & 0x1f) << shift;
      shift += 5;
    } while (byte >= 0x20);
    lon += (result & 1) ? ~(result >> 1) : (result >> 1);

    coords.push({ lat: lat / 1e5, lon: lon / 1e5 });
  }
  return coords;
}

function trafficFlowFromSpeed(speed) {
  switch (speed) {
    case 'TRAFFIC_JAM': return { density: 9, speed: 3.5, priority: 3 };
    case 'SLOW': return { density: 6, speed: 8.5, priority: 3 };
    default: return { density: 3, speed: 15, priority: 2 };
  }
}

function googleRoutePairsForBounds(minLon, minLat, maxLon, maxLat) {
  const cx = (minLon + maxLon) / 2;
  const cy = (minLat + maxLat) / 2;
  const dx = (maxLon - minLon) * 0.46;
  const dy = (maxLat - minLat) * 0.46;
  const p = {
    w: { lat: cy, lon: cx - dx },
    e: { lat: cy, lon: cx + dx },
    n: { lat: cy + dy, lon: cx },
    s: { lat: cy - dy, lon: cx },
    nw: { lat: cy + dy, lon: cx - dx },
    ne: { lat: cy + dy, lon: cx + dx },
    sw: { lat: cy - dy, lon: cx - dx },
    se: { lat: cy - dy, lon: cx + dx },
  };
  return [[p.w, p.e], [p.e, p.w], [p.n, p.s], [p.s, p.n], [p.nw, p.se], [p.ne, p.sw]];
}

async function buildGoogleTrafficRoads(minLon, minLat, maxLon, maxLat) {
  if (!GOOGLE_ROUTES_KEY) throw new Error('Google Routes key missing on server');
  const pairs = googleRoutePairsForBounds(minLon, minLat, maxLon, maxLat);
  const departureTime = new Date(Date.now() + 5 * 60_000).toISOString();
  const roads = [];

  for (let i = 0; i < pairs.length; i++) {
    const [origin, destination] = pairs[i];
    const body = {
      origin: { location: { latLng: { latitude: origin.lat, longitude: origin.lon } } },
      destination: { location: { latLng: { latitude: destination.lat, longitude: destination.lon } } },
      travelMode: 'DRIVE',
      routingPreference: 'TRAFFIC_AWARE_OPTIMAL',
      departureTime,
      extraComputations: ['TRAFFIC_ON_POLYLINE'],
      polylineQuality: 'HIGH_QUALITY',
      polylineEncoding: 'ENCODED_POLYLINE',
      computeAlternativeRoutes: false,
    };

    const resp = await fetch('https://routes.googleapis.com/directions/v2:computeRoutes', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Goog-Api-Key': GOOGLE_ROUTES_KEY,
        'X-Goog-FieldMask': 'routes.polyline.encodedPolyline,routes.travelAdvisory.speedReadingIntervals',
      },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(10_000),
    });

    if (!resp.ok) continue;
    const data = await resp.json();
    const route = data?.routes?.[0];
    const encoded = route?.polyline?.encodedPolyline;
    if (!encoded) continue;

    const points = decodeGooglePolyline(encoded);
    if (points.length < 2) continue;
    const intervals = route?.travelAdvisory?.speedReadingIntervals ?? [];

    if (!intervals.length) {
      const f = trafficFlowFromSpeed('NORMAL');
      roads.push({
        id: `g-${i}-all`,
        coords: points,
        density: f.density,
        speed: f.speed,
        priority: f.priority,
      });
      continue;
    }

    intervals.forEach((it, idx) => {
      const start = Math.max(0, it.startPolylinePointIndex ?? 0);
      const end = Math.min(points.length - 1, it.endPolylinePointIndex ?? points.length - 1);
      if (end - start < 1) return;
      const seg = points.slice(start, end + 1);
      if (seg.length < 2) return;
      const f = trafficFlowFromSpeed(it.speed ?? 'NORMAL');
      roads.push({ id: `g-${i}-${idx}`, coords: seg, density: f.density, speed: f.speed, priority: f.priority });
    });
  }

  return roads.map(r => ({
    ...r,
    totalLength: r.coords.reduce((sum, _, i) => i === 0 ? sum : sum + gcDistanceMeters(r.coords[i - 1].lat, r.coords[i - 1].lon, r.coords[i].lat, r.coords[i].lon), 0),
  }));
}

function parseTLEText(text) {
  const lines = text.split(/\r?\n/).map(l => l.trim()).filter(Boolean);
  const out = [];
  let pendingName = '';
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith('0 ')) { pendingName = line.slice(2).trim(); continue; }
    if (!line.startsWith('1 ')) continue;
    const line1 = line;
    const line2 = lines[i + 1] ?? '';
    if (!line2.startsWith('2 ')) continue;
    out.push({ name: pendingName || `SAT-${out.length + 1}`, line1, line2 });
    pendingName = '';
    i += 1;
  }
  return out;
}

async function ensureSatelliteCatalog(maxCount = 3000) {
  const now = Date.now();
  if (satCatalog.length && (now - satCatalogTs) < SAT_CATALOG_TTL_MS) return;

  async function loadFromCelesTrak() {
    const url = 'https://celestrak.org/NORAD/elements/gp.php?GROUP=active&FORMAT=TLE';
    const resp = await fetch(url, { headers: HEADERS, signal: AbortSignal.timeout(SAT_SNAPSHOT_POLL_TIMEOUT_MS) });
    if (!resp.ok) throw new Error(`CelesTrak ${resp.status}`);
    const text = await resp.text();
    const parsed = parseTLEText(text);
    const tle = Number.isFinite(maxCount) ? parsed.slice(0, maxCount) : parsed;
    satCatalog = tle.map((t, idx) => ({
      id: `${idx}:${t.name}`,
      name: t.name,
      satrec: satellite.twoline2satrec(t.line1, t.line2),
    }));
    satCatalogSource = 'celestrak';
  }

  async function loadFromSpaceTrack() {
    if (!SPACETRACK_USER || !SPACETRACK_PASS) {
      throw new Error('Space-Track credentials missing');
    }

    const loginBody = new URLSearchParams({
      identity: SPACETRACK_USER,
      password: SPACETRACK_PASS,
    });

    const loginResp = await fetch('https://www.space-track.org/ajaxauth/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...HEADERS,
      },
      body: loginBody.toString(),
      signal: AbortSignal.timeout(SAT_SNAPSHOT_POLL_TIMEOUT_MS),
    });
    if (!loginResp.ok) throw new Error(`Space-Track login ${loginResp.status}`);

    const cookie = loginResp.headers.get('set-cookie') ?? '';
    if (!cookie) throw new Error('Space-Track session cookie missing');

    // Omit limit clause → Space-Track returns their full GP catalog
    const queryUrl = `https://www.space-track.org/basicspacedata/query/class/gp/EPOCH/%3Enow-1/orderby/CREATION_DATE%20DESC/format/json`;
    const gpResp = await fetch(queryUrl, {
      headers: {
        ...HEADERS,
        Cookie: cookie,
      },
      signal: AbortSignal.timeout(SAT_SNAPSHOT_POLL_TIMEOUT_MS),
    });
    if (!gpResp.ok) throw new Error(`Space-Track GP ${gpResp.status}`);

    const rows = await gpResp.json();
    const allRows = (Array.isArray(rows) ? rows : []).filter(r => r?.TLE_LINE1 && r?.TLE_LINE2);
    const tleRows = Number.isFinite(maxCount) ? allRows.slice(0, maxCount) : allRows;
    satCatalog = tleRows.map((r, idx) => ({
      id: `${idx}:${r.OBJECT_NAME ?? r.NORAD_CAT_ID ?? 'SAT'}`,
      name: (r.OBJECT_NAME ?? `NORAD ${r.NORAD_CAT_ID ?? idx}`).trim(),
      satrec: satellite.twoline2satrec(r.TLE_LINE1, r.TLE_LINE2),
    }));
    satCatalogSource = 'spacetrack';
  }

  try {
    switch (BACKEND_SATELLITE_PROVIDER) {
      case 'spacetrack':
        await loadFromSpaceTrack();
        break;
      case 'n2yo':
        // N2YO has no practical bulk TLE feed for this snapshot mode.
        await loadFromCelesTrak();
        break;
      case 'celestrak':
      default:
        await loadFromCelesTrak();
        break;
    }
  } catch (err) {
    console.warn(`[proxy] Satellite catalog load failed (${BACKEND_SATELLITE_PROVIDER}), fallback to CelesTrak: ${err?.message ?? 'unknown'}`);
    await loadFromCelesTrak();
  }

  satCatalogTs = now;
}

function satelliteSnapshot(maxCount = 2000) {
  const nowDate = new Date();
  const gmst = satellite.gstime(nowDate);
  const points = [];
  const limit = Number.isFinite(maxCount) ? maxCount : satCatalog.length;
  for (let i = 0; i < satCatalog.length && points.length < limit; i++) {
    const s = satCatalog[i];
    const pv = satellite.propagate(s.satrec, nowDate);
    if (!pv?.position) continue;
    const geo = satellite.eciToGeodetic(pv.position, gmst);
    if (!Number.isFinite(geo.latitude) || !Number.isFinite(geo.longitude) || !Number.isFinite(geo.height)) continue;
    points.push({
      id: s.id,
      name: s.name,
      lat: toDeg(geo.latitude),
      lon: toDeg(geo.longitude),
      altM: geo.height * 1000,
    });
  }
  return points;
}

// ── Aircraft database ─────────────────────────────────────────────────────────
/** @type {Map<string, object>} */
const db = new Map();

function upsert(aircraft) {
  const now = Date.now();
  for (const a of aircraft) {
    const id = (a.hex ?? '').toLowerCase().trim();
    if (!id || !a.lat || !a.lon) continue;
    if (a.alt_baro === 'ground' || (a.alt_baro ?? 0) <= 100) continue;
    db.set(id, {
      hex:      id,
      flight:   (a.flight ?? a.r ?? '').trim(),
      lat:      a.lat,
      lon:      a.lon,
      alt_baro: a.alt_baro ?? a.alt_geom ?? 10000,
      track:    a.track ?? 0,
      gs:       a.gs ?? 0,
      // enrichment fields — used for icon shape, color classification, HUD panel
      t:        a.t        ?? '',       // ICAO type code e.g. "H60", "B738", "A320"
      category: a.category ?? '',       // ADS-B category byte e.g. "A7" = rotorcraft
      dbFlags:  a.dbFlags  ?? 0,        // bit 0 = military
      squawk:   a.squawk   ?? '',
      baro_rate: a.baro_rate ?? a.geom_rate ?? 0,
      _seen:    now,
    });
  }
}

function pruneStale() {
  const cutoff = Date.now() - STALE_MS;
  let n = 0;
  for (const [id, a] of db) { if (a._seen < cutoff) { db.delete(id); n++; } }
  if (n) console.log(`[proxy] Pruned ${n} — DB: ${db.size}`);
}

setInterval(pruneStale, 30_000);

// ── Hub selection — find hubs that overlap the viewport bbox ──────────────────

function hubsForBounds(minLon, minLat, maxLon, maxLat) {
  // Pad the bbox by one hub radius so we catch aircraft near the edges
  const pad = RADIUS_DEG * 1.1;
  const pMinLat = minLat - pad, pMaxLat = maxLat + pad;
  const pMinLon = minLon - pad, pMaxLon = maxLon + pad;
  const wraps = pMaxLon - pMinLon >= 360; // full globe visible

  return ALL_HUBS.filter(h => {
    if (h.lat < pMinLat || h.lat > pMaxLat) return false;
    if (wraps) return true;
    if (pMinLon < -180 || pMaxLon > 180) {
      // bbox wraps antimeridian
      return h.lon >= pMinLon + 360 || h.lon <= pMaxLon - 360 ||
             (h.lon >= pMinLon && h.lon <= pMaxLon);
    }
    return h.lon >= pMinLon && h.lon <= pMaxLon;
  });
}

// ── Hub fetcher with per-hub TTL cache ────────────────────────────────────────

async function fetchHub(hub) {
  const key = hubKey(hub);
  const cached = hubCache.get(key);

  // Return cached promise if hub was recently fetched
  if (cached) {
    if (cached.promise) return cached.promise; // in-flight
    if (Date.now() - cached.time < HUB_TTL) return; // fresh, skip
  }

  const promise = (async () => {
    try {
      const url = `https://opendata.adsb.fi/api/v3/lat/${hub.lat}/lon/${hub.lon}/dist/${RADIUS_NM}`;
      const res = await fetch(url, { headers: HEADERS, signal: AbortSignal.timeout(8_000) });
      if (!res.ok) throw new Error(`${res.status}`);
      const d = await res.json();
      upsert(d.aircraft ?? d.ac ?? []);
    } catch (err) {
      // Silently ignore individual hub failures
    } finally {
      hubCache.set(key, { time: Date.now(), promise: null });
    }
  })();

  hubCache.set(key, { time: Date.now(), promise });
  return promise;
}

// ── Request handler ───────────────────────────────────────────────────────────

async function handleFlights(query, res) {
  let hubs = [];
  const requestHeavy = query.mode === 'heavy' || SERVER_HEAVY_MODE;
  const viewportBufferDeg = requestHeavy ? 3 : 1;
  const parts = (query.bounds ?? '').split(',').map(Number);
  const bounds = (parts.length === 4 && parts.every(n => Number.isFinite(n))) ? parts : null;

  // Use configured backend provider where available; keep proxy hub mode as fallback.
  if (BACKEND_FLIGHT_PROVIDER === 'airplaneslive' || BACKEND_FLIGHT_PROVIDER === 'adsbool') {
    try {
      const base = BACKEND_FLIGHT_PROVIDER === 'airplaneslive'
        ? 'https://api.airplanes.live'
        : 'https://api.adsb.lol';
      // In server-heavy mode use /v2/all for global coverage (no viewport limit)
      await fetchReadsbProvider(base, bounds, requestHeavy);
    } catch (err) {
      console.warn(`[proxy] ${BACKEND_FLIGHT_PROVIDER} backend fetch failed, falling back to hub grid: ${err?.message ?? 'unknown'}`);
    }
  }

  if (BACKEND_FLIGHT_PROVIDER === 'proxy' || BACKEND_FLIGHT_PROVIDER === 'opensky') {
    // In heavy mode fetch ALL hubs globally; otherwise only viewport hubs
    if (requestHeavy) {
      hubs = ALL_HUBS;
    } else if (bounds) {
      const [minLon, minLat, maxLon, maxLat] = bounds;
      hubs = hubsForBounds(minLon, minLat, maxLon, maxLat);
    }

    const batches = [];
    for (let i = 0; i < hubs.length; i += MAX_CONC) {
      batches.push(hubs.slice(i, i + MAX_CONC));
    }
    for (const batch of batches) {
      await Promise.allSettled(batch.map(h => fetchHub(h)));
    }
  }

  // In server-heavy mode return the entire DB (global mode); otherwise filter to bbox
  let aircraft = [...db.values()].map(({ _seen, ...rest }) => rest);

  if (!requestHeavy && bounds) {
    const [minLon, minLat, maxLon, maxLat] = bounds;
    aircraft = aircraft.filter(a =>
      a.lat >= minLat - viewportBufferDeg && a.lat <= maxLat + viewportBufferDeg &&
      a.lon >= minLon - viewportBufferDeg && a.lon <= maxLon + viewportBufferDeg
    );
  }

  console.log(`[proxy] flights=${BACKEND_FLIGHT_PROVIDER} ${hubs.length} hubs queried → ${aircraft.length} aircraft in viewport${requestHeavy ? ' (heavy)' : ''}`);

  res.writeHead(200);
  res.end(JSON.stringify({ aircraft, total: aircraft.length, ts: Date.now(), source: BACKEND_FLIGHT_PROVIDER }));
}

// ── HTTP server ───────────────────────────────────────────────────────────────

const server = http.createServer(async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Content-Type', 'application/json');
  if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }

  const [path, qs] = req.url.split('?');
  const query = Object.fromEntries(new URLSearchParams(qs ?? ''));
  const url   = path.replace(/\/$/, '');

  if (url === '/api/flights') {
    await handleFlights(query, res);
  } else if (url === '/api/traffic/google') {
    const parts = (query.bounds ?? '').split(',').map(Number);
    if (parts.length !== 4 || parts.some(n => !Number.isFinite(n))) {
      res.writeHead(400);
      res.end(JSON.stringify({ error: 'bounds must be minLon,minLat,maxLon,maxLat' }));
      return;
    }
    try {
      const [minLon, minLat, maxLon, maxLat] = parts;
      const roads = await buildGoogleTrafficRoads(minLon, minLat, maxLon, maxLat);
      res.writeHead(200);
      res.end(JSON.stringify({ roads, total: roads.length, ts: Date.now(), source: 'google-routes-server' }));
    } catch (err) {
      res.writeHead(502);
      res.end(JSON.stringify({ error: err?.message ?? 'traffic request failed' }));
    }
  } else if (url === '/api/satellites/snapshot') {
    const rawMax = parseInt(query.max ?? '0', 10);
    // 0 or missing → no limit (full catalog); otherwise honour the requested count
    const maxCount = rawMax > 0 ? rawMax : Infinity;
    try {
      await ensureSatelliteCatalog(maxCount);
      const points = satelliteSnapshot(maxCount);
      res.writeHead(200);
      res.end(JSON.stringify({ points, total: points.length, ts: Date.now(), source: `server-propagated:${satCatalogSource}` }));
    } catch (err) {
      res.writeHead(502);
      res.end(JSON.stringify({ error: err?.message ?? 'satellite snapshot failed' }));
    }
  } else if (url === '/health') {
    res.writeHead(200);
    res.end(JSON.stringify({ status: 'ok', db: db.size, hubs: ALL_HUBS.length, hub_cache: hubCache.size }));
  } else {
    res.writeHead(404);
    res.end(JSON.stringify({ error: 'Not found' }));
  }
});

server.listen(PORT, () => {
  console.log(`[proxy] Mode: ${SERVER_HEAVY_MODE ? 'heavy' : 'normal'}`);
  console.log(`[proxy] Providers: flights=${BACKEND_FLIGHT_PROVIDER}, satellites=${BACKEND_SATELLITE_PROVIDER}`);
  console.log(`[proxy] ShadowGrid → http://localhost:${PORT}/api/flights?bounds=minLon,minLat,maxLon,maxLat`);
});
